// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3TSp-kMwiBsErKdD8L-aSKdzDfYT_kV4',
    appId: '1:32487306530:web:f161397f53a1f96a6a617b',
    messagingSenderId: '32487306530',
    projectId: 'flutter-crud-6bdc0',
    authDomain: 'flutter-crud-6bdc0.firebaseapp.com',
    storageBucket: 'flutter-crud-6bdc0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD69a5ORbMH2W4zYXOdpccG7_GzEwQ5xHc',
    appId: '1:32487306530:android:71f49deede15be5e6a617b',
    messagingSenderId: '32487306530',
    projectId: 'flutter-crud-6bdc0',
    storageBucket: 'flutter-crud-6bdc0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFbHqPmJWyGwT5B5kclTkYrEcZNByHxps',
    appId: '1:32487306530:ios:284d1b99ada34b9b6a617b',
    messagingSenderId: '32487306530',
    projectId: 'flutter-crud-6bdc0',
    storageBucket: 'flutter-crud-6bdc0.appspot.com',
    iosClientId: '32487306530-5jchifrhg4se7ave8vkf28d2ptp9apaq.apps.googleusercontent.com',
    iosBundleId: 'com.example.crudFire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFbHqPmJWyGwT5B5kclTkYrEcZNByHxps',
    appId: '1:32487306530:ios:284d1b99ada34b9b6a617b',
    messagingSenderId: '32487306530',
    projectId: 'flutter-crud-6bdc0',
    storageBucket: 'flutter-crud-6bdc0.appspot.com',
    iosClientId: '32487306530-5jchifrhg4se7ave8vkf28d2ptp9apaq.apps.googleusercontent.com',
    iosBundleId: 'com.example.crudFire',
  );
}
